---
title: "acknowledgements"
author: "Abbas Rizvi"
date: "9/14/2018"
output: pdf_document  
---

```{r ack_setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I would like to express my deepest gratitude to my adviser Dr. Lara Sucheston-Campbell. She has been an incredible mentor for me and has set me up with any and every opportunity that I have had my eyes on. She really cares about her students and I am truly grateful for that. 

I am forever indebted to my Master's adviser, Dr. Barbara Foster, for taking a chance on me and working her magic to get me an opportunity to interview for a PhD position at RPCI. This was done despite the application cycle closing several months beforehand, the incoming class was full, and the next academic year was beginning in a matter of weeks.

Dr. Martin Morgan exposed to me wealth of knowledge on R and would take time out of his extremely busy schedule to work one-on-one with me. Dr. Moray Campbell set me up with a career defining opportunity where I went to Europe for a year and began my journey of pursuing quantitative biology. Dr. Seb Battaglia, my Master's co-adivser, his training contributed to my successes in graduate school.

And thank you to Ezgi Karaesmen, I truly believe I would not had the level of success I have had for past four years if it were not for you. Your love, your support, your intelligence, and your ability to challenge me on my scientific ideas and my ability to think have been instrumental towards my development as a scientist, I cannot thank you enough. 

This work was supported by National Institute of Health/National Heart, Blood, and Lung Institute R01HL102278 and National Institute of Health/National Cancer Institute R03CA188733. Support provided by Center for Computational Research at University at Buffalo.